# Generated by Django 5.2.8 on 2025-11-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '問', 'verbose_name_plural': '問'},
        ),
        migrations.AddField(
            model_name='choice',
            name='position',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Position'),
        ),
    ]
