# Generated by Django 5.2.8 on 2025-11-19 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': '設問', 'verbose_name_plural': '設問'},
        ),
    ]
