# Generated by Django 5.2.8 on 2025-11-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_question_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['position'], 'verbose_name': '選択肢', 'verbose_name_plural': '選択肢'},
        ),
    ]
