# Generated by Django 5.2.8 on 2025-11-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_alter_choice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=255, verbose_name='予約番号')),
                ('status', models.TextField(choices=[('予約', '予約'), ('チェックイン', 'チェックイン'), ('完了', '完了'), ('キャンセル', 'キャンセル'), ('ドタキャン', 'ドタキャン')], max_length=255, verbose_name='ステータス')),
            ],
            options={
                'verbose_name': '予約',
                'verbose_name_plural': '予約',
            },
        ),
    ]
