# Generated by Django 5.2.8 on 2025-11-19 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='questions',
            field=models.ManyToManyField(to='polls.question'),
        ),
    ]
