# Generated by Django 5.2.8 on 2025-11-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_reservation_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='questions',
            field=models.ManyToManyField(blank=True, to='polls.question'),
        ),
    ]
